Setup Totp model and factories
bloom-solutions/stellar_multisig-rails pull request #2
Opened 2018-11-20 11:49 UTC by jaspervanbrian

- Install byebug for debugging
- Create migration for totp
- Fix 'Factory not defined'
- Add stellar-sdk dependency
- Default to rbnacl 5.0.0 (v6.0.0 doesn't support rbnacl-libsodium)
- Require factory_bot_rails instead of factory_bot

2018-11-22 00:34 UTC, ramontayag requested changes

2018-11-22 00:34 UTC, ramontayag commented on .byebug_history
> +q
@jaspervanbrian what's this file for?

2018-11-22 00:34 UTC, ramontayag commented on app/controllers/stellar_multisig/rails/api/v1/totp_controller.rb
> +module StellarMultisig::Rails
@jaspervanbrian it looks having `::Rails` for a Rails engine [is recommended](https://stackoverflow.com/a/8961409/61018), but it bothers me that the migrations have a `rails` in the table name.

2018-11-22 00:34 UTC, ramontayag commented on app/controllers/stellar_multisig/rails/api/v1/totp_controller.rb
> +module StellarMultisig::Rails
I think what will work is to [set the engine name](https://edgeapi.rubyonrails.org/classes/Rails/Engine.html) like:

```ruby
module MyEngine
  class Engine < Rails::Engine
    engine_name "my_engine"
  end
end
```

Then, when you create migrations, `rails` should not be there anymore.

2018-11-22 00:34 UTC, ramontayag commented on stellar_multisig-rails.gemspec
> +  s.add_dependency "rbnacl", "~> 5.0.0"
```suggestion
  s.add_dependency "rbnacl", "< 6.0"
```

2018-11-30 11:40 UTC, jaspervanbrian commented
I removed `::Rails` from `isolate_namespace`, because when you generate something like a model or a controller, it auto nests it with the namespace you provided in the `isolate_namespace`.

I did this because it is easier to generate controller with a `Rails` namespace by just `rails g Rails::<controller_path>` command, than to avoid a migration with a `_rails_` name on it.

I also added the engine_name "/stellar_multisig", because it looks much more nicer than "/stellar_multisig-rails"

2018-11-30 18:43 UTC, jaspervanbrian commented
Actual format of the provisioning_uri:
```
otpauth://totp/<issuer>:<string_provided>?secret=<totp.secret>&issuer=<totp.issuer>
```

```
totp = ROTP::TOTP.new("asd", issuer: "qwe")
totp.provisioning_uri("alice@google.com") 
# => 'otpauth://totp/qwe:alice@google.com?secret=asd&issuer=qwe'
```

2018-12-12 01:40 UTC, ramontayag approved these changes

2018-12-12 02:09 UTC, merged